modLoader="lowcodefml"
loaderVersion="*"
issueTrackerURL="https://github.com/SlimeKnights/TinkersThings/issues"
license="MIT"
[[mods]]
    modId="tinkers_things"
    version="1.3.1"
    displayName="Tinkers' Things"
    description='''
    A fully playable example Thing Pack for Tinkers' Construct. Includes example tools, weapon, and material.
    '''
[[dependencies.tinkers_things]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.9.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_things]]
    modId="jsonthings"
    mandatory=true
    versionRange="[0.9.9,)"
    ordering="NONE"
    side="BOTH"
